name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Run benchmarks
      run: cargo bench -- --output-format json | tee benchmark_results.json
      
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: benchmark_results.json
        # Auto-push results to gh-pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Comment on PRs with performance changes
        comment-on-alert: true
        alert-threshold: '200%'  # Alert if performance degrades 2x
        fail-on-alert: true      # Fail CI if performance degrades significantly
