name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run doc tests
        run: cargo test --doc

  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    needs: test
    defaults:
      run:
        working-directory: ./rust
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.pull_request.changed_files, 'src/trie.rs') ||
      contains(github.event.pull_request.changed_files, 'src/trie_node.rs') ||
      contains(github.event.pull_request.changed_files, 'benches/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}
      - name: Run benchmarks
        run: cargo bench
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion/
=======
    needs: test  # ← Only run if tests pass!
=======
    needs: test # ← Only run if tests pass!
>>>>>>> 4f19b68 (Changed benchmark conditional check)
    defaults:
      run:
        working-directory: ./rust

    # Only run benchmarks on main branch or when PR affects performance-critical files
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.pull_request.changed_files, 'src/trie.rs') ||
      contains(github.event.pull_request.changed_files, 'src/trie_node.rs') ||
      contains(github.event.pull_request.changed_files, 'benches/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

      - name: Run benchmarks
        run: cargo bench -- --output-format json | tee benchmark_results.json

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: "150%" # Alert if performance degrades 50%
          fail-on-alert: false # Don't fail CI, just alert

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            benchmark_results.json
            target/criterion/
=======
    needs: test  # ← Only run if tests pass!
=======
    needs: test # ← Only run if tests pass!
>>>>>>> 900397b (Changed benchmark conditional check)
    defaults:
      run:
        working-directory: ./rust

    # Only run benchmarks on main branch or when PR affects performance-critical files
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.pull_request.head.repo.git_refs_url, 'src/trie.rs') ||
      contains(github.event.pull_request.head.repo.git_refs_url, 'src/trie_node.rs')

    steps:
<<<<<<< HEAD
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run benchmarks
      run: cargo bench -- --output-format json | tee benchmark_results.json
      
    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: benchmark_results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        alert-threshold: '150%'  # Alert if performance degrades 50%
        fail-on-alert: false     # Don't fail CI, just alert
        
    - name: Upload benchmark artifacts
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: |
          benchmark_results.json
          target/criterion/
>>>>>>> a269de2 (I have moved the actions out of the rust folder into the root folder)
=======
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

      - name: Run benchmarks
        run: cargo bench -- --output-format json | tee benchmark_results.json

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: "150%" # Alert if performance degrades 50%
          fail-on-alert: false # Don't fail CI, just alert

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            benchmark_results.json
            target/criterion/
>>>>>>> 900397b (Changed benchmark conditional check)

  # Optional: Additional checks
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust

    steps:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> a269de2 (I have moved the actions out of the rust folder into the root folder)
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install cargo-audit
      run: cargo install cargo-audit
      
    - name: Run security audit
      run: cargo audit
<<<<<<< HEAD
>>>>>>> 3ca6ad7 (I have moved the actions out of the rust folder into the root folder)
=======
=======
>>>>>>> 900397b (Changed benchmark conditional check)
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit
<<<<<<< HEAD
>>>>>>> 4f19b68 (Changed benchmark conditional check)
=======
>>>>>>> a269de2 (I have moved the actions out of the rust folder into the root folder)
=======
>>>>>>> 900397b (Changed benchmark conditional check)
