name: Rust Benchmark

on:
  push:
    branches: [main]

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./rust
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.pull_request.changed_files, 'src/trie.rs') ||
      contains(github.event.pull_request.changed_files, 'src/trie_node.rs') ||
      contains(github.event.pull_request.changed_files, 'benches/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify benchmark files exist
        run: |
          echo "Checking for benchmark files..."
          find . -name "*.rs" -path "*/benches/*" -o -name "*bench*.rs" | head -10
          echo "Cargo.toml bench configuration:"
          grep -A 5 -B 5 "bench" Cargo.toml || echo "No bench configuration found"

      - name: Run benchmarks
        run: |
          echo "Running Rust benchmarks..."
          cargo bench --verbose
          echo "Benchmark run complete"

      - name: Verify benchmark artifacts were created
        run: |
          echo "Checking for Criterion output..."
          if [ -d "target/criterion" ]; then
            echo "✅ target/criterion directory exists"
            find target/criterion -type f | head -20
            echo "Total files in target/criterion: $(find target/criterion -type f | wc -l)"
          else
            echo "❌ target/criterion directory not found"
            echo "Available directories in target/:"
            ls -la target/ || echo "target/ directory doesn't exist"

            # Create empty directory with a README to avoid upload failure
            mkdir -p target/criterion
            echo "# Benchmark Results" > target/criterion/README.md
            echo "No benchmark results were generated in this run." >> target/criterion/README.md
            echo "This may indicate:" >> target/criterion/README.md
            echo "- No benchmark files found" >> target/criterion/README.md
            echo "- Benchmark compilation failed" >> target/criterion/README.md
            echo "- Criterion not properly configured" >> target/criterion/README.md
          fi

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: rust/target/criterion/
          retention-days: 30
          if-no-files-found: warn
